### ISSUE TITLE
deep learning h20

### ISSUE THREAD

**Issue by Noor59007** [h2oai/h2o-training-book#2]
model <- h2o.deeplearning(x = 2:1025,
+                           y = 1,
+                           training_frame = train_h2o,
+                           activation = "RectifierWithDropout", 
+                           input_dropout_ratio = 0.2,
+                           hidden_dropout_ratios = c(0.5,0.5,.5),
+                           balance_classes = TRUE, 
+                           hidden = c(64,64,64),
+                           epochs = 500)
Error in .h2o.validateModelParameters(algo, param_values, h2oRestApiVersion) : 
  Too many levels in response column: 15000, maximum supported number of classes is 1000..

**Comment by likesxuqiang** [comment]
how do you solve this ?

**Comment by Noor59007** [comment]
Check your y column(number of classes)
