### ISSUE TITLE
Anomaly Detection Example Needs Slight Edit

### ISSUE THREAD

**Issue by rajshah4** [h2oai/h2o-training-book#3]
When I was trying the anomaly detection, I found that h2o in R wants the information as object and then data.  So instead of: h2o.anomaly(test_hex, ae_model)  
The code should read h2o.anomaly(ae_model, test_hex)  
Hope this fix makes sense, it fixed the issue for me

**Comment by arnocandel** [comment]
The new h2o-3 R API looks like you describe, but this example was made for h2o-classic aka h2o-2 in 2014, where the arguments were flipped. Thanks for reporting though! We are working on improved documentation that remains up-to-date.
